copypedia/Models/Article.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace copypedia.Models
{
    public class Article
    {
        public int ArticleId { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }

        [Required]
        [Display(Name = "Created on")]
        [DataType(DataType.DateTime)]
        public DateTime CreationDateTime { get; set; } = DateTime.Now;

        [Required]
        public bool IsEditable { get; set; } = true;

        public virtual ApplicationUser Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual List<ArticleDiff> Diffs { get; set; } = new List<ArticleDiff>();
    }
}

copypedia/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using copypedia.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace copypedia.Controllers
{
    [Authorize(Roles = "User,Editor,Admin")]
    public class ArticlesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Articles
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Articles.ToList());
        }

        // GET: Articles/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // GET: Articles/Create
        [AllowAnonymous]
        public ActionResult Create()
        {
            ViewBag.CategoryNames = db.Categories.Select(x => x.Name);
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)] // TODO: Enable input validation ??
        [AllowAnonymous]
        public ActionResult Create([Bind(Include = "Title,Content")] Article article, string CategoryName)
        {
            if (ModelState.IsValid)
            {
                var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                ArticleDiff diff = new ArticleDiff
                {
                    Author = Request.IsAuthenticated ? userManager.FindByName(User.Identity.Name) : userManager.FindByName("Unknown"),
                    Message = "Article created",
                    Content = article.Content,
                    CreationDateTime = DateTime.Now,
                };
                article.Diffs.Add(diff);
                article.Category = db.Categories.Where(x => x.Name == CategoryName).First();
                article.Author = Request.IsAuthenticated ? userManager.FindByName(User.Identity.Name) : userManager.FindByName("Unknown");
                article.CreationDateTime = DateTime.Now;
                db.Articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: Articles/Edit/5
        [AllowAnonymous]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            if (!article.IsEditable && User.Identity.Name != article.Author.UserName)
            {
                ViewBag.Message = "This article has been locked and cannot be edited right now... :(";
                return View("Error");
            }
            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)] // TODO: Enable input validation ??
        [AllowAnonymous]
        public ActionResult Edit([Bind(Include = "ArticleId,Title,Content")] Article x, string message)
        {
            if (ModelState.IsValid)
            {
                Article article = db.Articles.Find(x.ArticleId);
                if (!article.IsEditable && !Request.IsAuthenticated)
                {
                    // TODO: Show that article is not editable instead of BadRequest
                    ViewBag.Message = "This article has been locked and cannot be edited right now :(";
                    return View("Error");
                }
                var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                ArticleDiff diff = new ArticleDiff
                {
                    Author = Request.IsAuthenticated ? userManager.FindByName(User.Identity.Name) : userManager.FindByName("Unknown"),
                    Message = message,
                    Content = x.Content,
                    CreationDateTime = DateTime.Now,
                };
                article.Diffs.Add(diff);
                article.Title = x.Title;
                article.Content = x.Content;
                //db.ArticleDiffs.Add(diff);
                db.Entry(article).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(x);
        }

        // GET: Articles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Article article = db.Articles.Find(id);
            article.Diffs.Clear();
            db.Articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public ActionResult Search(string s)
        {
            var q = from x in db.Articles
                    where x.Title.Contains(s) || x.Content.Contains(s)
                    select x;
            return View(q);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SetEditable([Bind(Include = "ArticleId,IsEditable")] Article x)
        {
            Article article = db.Articles.Find(x.ArticleId);
            if (article.Author.UserName != User.Identity.Name && User.IsInRole("User"))
            {
                ViewBag.Message = "This article has been locked and cannot be edited right now :(";
                return View("Error");
            }
            article.IsEditable = x.IsEditable;
            db.Entry(article).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Details", new { id = article.ArticleId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

copypedia/Views/Articles/Create.cshtml
@model copypedia.Models.Article

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Article</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryName", new SelectList(ViewBag.CategoryNames))
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextArea("Content", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

copypedia/Views/Articles/Delete.cshtml
@model copypedia.Models.Article

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsEditable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsEditable)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

copypedia/Views/Articles/Details.cshtml
@using copypedia.Models;


@model copypedia.Models.Article

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h1>@Model.Title</h1>
        @Html.Raw(Model.Content)
    </div>
</div>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h3>Changes</h3>
        <table class="table table-bordered">
            <tr>
                <th>Created on</th>
                <th>Message</th>
                <th>Author</th>
            </tr>
            @* TODO: Add table headers *@
            @foreach (ArticleDiff diff in Model.Diffs)
            {
            <tr>
                <td>@diff.CreationDateTime</td>
                <td>@Html.RouteLink(diff.Message, new { action = "Details", controller = "ArticleDiffs", id = diff.ArticleDiffId })</td>
                <td>@Html.RouteLink(diff.Author.UserName, new { action = "Details", controller = "Users", id = diff.Author.Id })</td>
            </tr>
            }
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.ArticleId }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
    <div class="col-md-6">
        <dl class="dl-horizontal pull-right">
            <dt>
                Author
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Author.UserName)
            </dd>
            @if (Request.IsAuthenticated)
            {
                if (User.Identity.Name.Equals(Model.Author.UserName) || !User.IsInRole("User"))
                {
                    using (Html.BeginForm("SetEditable", "Articles", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.ArticleId)
                        <dt>
                            @Html.LabelFor(model => model.IsEditable)
                        </dt>
                        <dd>
                            @Html.EditorFor(model => model.IsEditable)
                            <input class="form-control" type="submit" value="Save editable status" />
                        </dd>
                    }
                }
            }
        </dl>
    </div>
</div>

copypedia/Views/Articles/Edit.cshtml
@model copypedia.Models.Article

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Article</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ArticleId)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Edit message", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Editor("Message", new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

copypedia/Views/Articles/Index.cshtml
@model IEnumerable<copypedia.Models.Article>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @item.Title
        </td>
        <td>
            @item.Author.UserName
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ArticleId }) |
            @Html.ActionLink("Details", "Details", new { id = item.ArticleId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ArticleId })
        </td>
    </tr>
}

</table>

copypedia/Views/Articles/Search.cshtml
@model IEnumerable<copypedia.Models.Article>

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreationDateTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td class="search-result">
            @Html.ActionLink(item.Title, "Details", new { controller = "Articles", id = item.ArticleId })
        </td>
        <td class="search-result">
            @Html.DisplayFor(modelItem => item.Content)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreationDateTime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ArticleId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ArticleId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ArticleId })
        </td>
    </tr>
}

</table>

@section scripts {
    <script>
        var s = "@Request.Params[0]";
        var highlight = "<span class='search-highlight'>" + s + "</span>";
        $(".search-result").each(function () {
            var text = $(this).html();
            $(this).html(text.replace(new RegExp(s, 'g'), highlight));
        });
    </script>
}